
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bd4be6c1-cd51-41ac-93ae-74d8e6788952",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YM65ESL0W",
    "aws_user_pools_web_client_id": "5m9qtaekhhhqnhd37mittqf8mq",
    "oauth": {
        "domain": "saddlefit.auth.us-east-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost:3000/dashboard",
        "redirectSignOut": "http://localhost:3000/dashboard",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "GIVEN_NAME",
        "FAMILY_NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "saddlefit-dev-saddlefitpublicbucket-wtkzvtly29n8",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;


// ---prod----

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:79b22c1d-6110-412d-a69e-8a43ffb7e0f1",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_KlwB4XIIJ",
//     "aws_user_pools_web_client_id": "6ecfqrnqdkphrkgcfpipjru85",
//     "oauth": {
//         "domain": "saddlefit.auth.us-east-2.amazoncognito.com",
//         "scope": [
//             "email",
//             "openid",
//             "phone",
//             "profile"
//         ],
//         "redirectSignIn": "http://localhost:3000/dashboard",
//         "redirectSignOut": "http://localhost:3000/dashboard",
//         "responseType": "token"
//     },
//     "federationTarget": "COGNITO_USER_POOLS",
//     "aws_cognito_username_attributes": [
//         "EMAIL"
//     ],
//     "aws_cognito_social_providers": [],
//     "aws_cognito_signup_attributes": [
//         "EMAIL",
//         "GIVEN_NAME",
//         "FAMILY_NAME"
//     ],
//     "aws_cognito_mfa_configuration": "OFF",
//     "aws_cognito_mfa_types": [],
//     "aws_cognito_password_protection_settings": {
//         "passwordPolicyMinLength": 8,
//         "passwordPolicyCharacters": [
//             "REQUIRES_LOWERCASE",
//             "REQUIRES_UPPERCASE",
//             "REQUIRES_NUMBERS",
//             "REQUIRES_SYMBOLS"
//         ]
//     },
//     "aws_cognito_verification_mechanisms": [
//         "EMAIL"
//     ]
// };


// export default awsmobile;
